spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.1c177a3ef00c741a
            client-secret: a27adddd9de4a6d5a2ee62f98e6b1236a03df78c
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

#logging:
#  level:
#    org.springframework.security: DEBUG
